//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MpToPatient
    {
        public int MpToPatientId { get; set; }
        public Nullable<int> MPId { get; set; }
        public Nullable<int> PatientId { get; set; }
    
        public virtual MedicalProfessional MedicalProfessional { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
