//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientUsage
    {
        public int PatientUsageId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> ScriptId { get; set; }
        public Nullable<int> MedicationId { get; set; }
        public Nullable<System.DateTime> DateTaken { get; set; }
    
        public virtual Medication Medication { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Script Script { get; set; }

        public PatientUsage(Script script)
        {
            PatientId = script.PatientId;
            ScriptId = script.ScriptId;
            MedicationId = script.MedicationId;
        }
    }
}
