//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PharmacyEvent
    {
        public int Id { get; set; }
        public int ScriptId { get; set; }
        public Nullable<System.DateTime> DateFilled { get; set; }
        public Nullable<System.DateTime> DatePickedUp { get; set; }
    
        public virtual Script Script { get; set; }
    }
}
