//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Script
    {
        public int ScriptId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> MedicationId { get; set; }
        public Nullable<int> MPId { get; set; }
        public Nullable<int> PharmId { get; set; }
        public string Dosage { get; set; }
        public string MedicationTime { get; set; }
        public string MedicationRoute { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public Nullable<System.DateTime> DateFilled { get; set; }
        public Nullable<System.DateTime> DatePickedUp { get; set; }
    
        public virtual MedicalProfessional MedicalProfessional { get; set; }
        public virtual Medication Medication { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Pharmacy Pharmacy { get; set; }
    }
}
